---
title: "stl_lead_inequity"
format: html
editor: visual
excute: 
  warning: FALSE
---

## Day 1 Activity 

```{r}
# load packages 
library(tidyverse)
library(janitor)
#| warning: false 
#| message: false 
```

```{r}
# getting the data
stl_blood_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))

# cleaning the data 
stl_blood_lead <- stl_blood_lead %>% clean_names()

# calling the data 
stl_blood_lead
```

```{r}
# data exploration 
skimr::skim(stl_blood_lead)

dim(stl_blood_lead)
names(stl_blood_lead)
```


```{r}
# adding a column 
stl_lead_prop <- stl_blood_lead %>% dplyr::mutate(prop_white = (white / total_pop) * 100)
```

```{r}
# create a scatter plot 
stl_blood_lead_scatter <- ggplot(data = stl_lead_prop, 
       aes(x = pct_elevated, y = prop_white)) + 
  geom_point () + 
  theme_classic () +
  labs (title = "Elevated Blood Lead Levels", 
        x = "Childern with Elevated Blood Lead Levels (% per census)", 
        y = "Identifying as White (% per census)") 

#export plot 
ggsave(here::here("figs", "stl_lead_plot.png"), height = 5, width = 6)

```

```{r}
# Making a cooler scatter plot 
stl_blood_lead_smooth <- ggplot(data = stl_lead_prop, 
       aes(x = pct_elevated, y = prop_white)) + 
  geom_smooth () + 
  theme_classic () +
  labs (title = "Elevated Blood Lead Levels", 
        x = "Childern with Elevated Blood Lead Levels (% per census)", 
        y = "Identifying as White (% per census)", 
        caption = "The population idenitfying as white have less childern with elevated blood lead levels.") 

#export plot 
ggsave(here::here("figs", "stl_lead_plotUPDATED.png"), height = 5, width = 6)
```

```{r}
# Creating a histogram 
ggplot(data = stl_lead_prop, 
       aes(x = pct_elevated)) + 
  geom_histogram (color="purple", fill = "pink") + 
  theme_classic() +
  labs(title = "Elevated Blood Lead Levels", 
       x = "Percentages of Childern's Elevated Blood Lead Levels", 
       y = "Frequency")

#export plot 
ggsave(here::here("figs", "stl_lead_histogram.jpg"), height = 5, width = 6)
```

